### ISSUE TITLE
Question: Where are the default preset values defined?

### ISSUE THREAD

**Issue by GavinRay97** [dvize/Donuts#39]
I've tried to grep the codebase for `starting-pmcs` but I can't seem to find anything.

Curious how the default preset configs and JSON files are defined + written out?
Thank you =)

(I ask because I am testing the `GUI` branch which doesn't seem to have a UI yet for swapping presets, and I want to change to `starting-pmcs-only-live-like` but it seems to use the display name as the preset, which I'm unsure of exactly:

```json
{
  "pmcScenarioSelection": "Live Like (Random)",
}
```

![image](https://github.com/dvize/Donuts/assets/26604994/5ce45b1b-4b69-4acb-a1a5-321ccc08d962)

**Comment by dvize** [comment]
The default values are defined in DefaultPluginVars > DefaultPluginVars.
There is a constructor with the same name inside that cs file that has default values defined.  Similar to how bepinex config is setup
