### ISSUE TITLE
HotSpot Ignore Hard Cap not working as of 1.4.4

### ISSUE THREAD

**Issue by Celsjusz** [dvize/Donuts#44]
Hey.

this commit https://github.com/dvize/Donuts/commit/38d26d951adc595bbc9918134277b655efb3c717 broke HotSpot Ignore Hard Cap 
![obraz](https://github.com/dvize/Donuts/assets/17830288/8c3d23a9-c1f4-4fe0-8bd5-93d33ce661eb)

after this commit that check is no longer done in code. 
![obraz](https://github.com/dvize/Donuts/assets/17830288/46859ebd-b1fe-405d-9bef-4aed185e6b8c)
This new chunk of code doesn't include HotSpot Ignore Hard Cap. I've done testing in game also and once `Hard Cap` is enabled with `HotSpot Ignore Hard Cap` the bots don't spawn(even with `HotSpot Boost` enabled). This involves both PMC and SCAV options.

**Comment by p-kossa** [comment]
keeping this open since the hard cap is still a little buggy

**Comment by p-kossa** [comment]
I'm assuming this is fixed, I haven't seen reports of this not working since, will re-open if necessary
