### ISSUE TITLE
"Live Like (Random)" raid preset contains "starting-pmcs-only-live-like-alt". 

### ISSUE THREAD

**Issue by Sephta** [dvize/Donuts#70]
Configured donuts to pick Live Like (Random) presets but a starting pmc preset was selected.

Steps to reproduce:

1. launch tarkov and open donuts config menu
2. under "PMC Raid Spawn Preset Selection" choose "Live Like (Random)"
3. launch a raid on Ground Zero
4. open the console and see which preset was selected in the logs

Expected Result: pool of presets does not contain "starting-pmc-only" presets

Actual Result: pool does contain "starting-pmc-only" presets

This issue was seen on latest RC5 build from Nooky

**Comment by p-kossa** [comment]
fixed with https://github.com/dvize/Donuts/commit/e7ef402dde78a0aaea9cc68ea93102cd290fb842
