### ISSUE TITLE
Donuts spam the log makes game crash

### ISSUE THREAD

**Issue by 0w0-Yui** [dvize/Donuts#77]
![Snipaste_2024-07-24_14-59-02](https://github.com/user-attachments/assets/815a62b9-7c9f-4dd8-9aa1-a408de3c0e25)
![Snipaste_2024-07-24_14-58-49](https://github.com/user-attachments/assets/4cd63e06-2064-4acf-a98c-40be9939c140)
[FullLogOutput.log](https://github.com/user-attachments/files/16358397/FullLogOutput.log)
Can't upload the LogOutput.log, it's way too big

**Comment by p-kossa** [comment]
@0w0-Yui hey thanks for the report. can I see your Donuts settings? DefaultPluginVars

Also, I'm assuming this is the latest ver. 3.5.1 of S+D? are you able to reproduce this?

**Comment by p-kossa** [comment]
closing this, please feel free to re-open if necessary
